t=input()
print(f'Длина: {len(t)}')
print(f'Верхний регистр: {t.upper()}')
print(f'Нижний регистр: {t.lower()}')
print(f'Первый символ: {t[0]}')
print(f'Последний символ: {t[-1]}')
print(f'Количество пробелов: {t.count(' ')}')
